# Simulation Configuration File

satellite:
      # physical properties
      mass : 1.0 # kg
      area : 0.01 # face area m^2
      inertia : [[0.00149, 0.0, 0.00014], [0.0, 0.00147, 0.0],[0.00014, 0.0, 0.00154]]
      Cd : 2.2 # Drag coefficient
      
      # Reaction Wheels
      N_rw : 1                   # number of reaction wheels
      rw_orientation : [[0,0,1]] # spin axis of each reaction wheel in the body frame
      I_rw : 6.5e-7              # kg.m^2 inertia of each reaction wheel
      m_rw: 0.002                # kg mass of each reaction wheel
      max_torque : 0.001         # N.m maximum torque that can be applied by each reaction wheel
      max_speed : 600            # rad/s maximum speed that can be achieved by each reaction wheel

      # Magnetorquers
      mtb:
            N_mtb : 6                                     # number of magnetorquers
            mtb_orientation : [[1,0,0], [0,1,0], [0,0,1], [1,0,0], [0,1,0], [0,0,1]] # alignment axis of each magnetorquer in the body frame
            max_voltage : [5,5,5,5,5,5]                          # V maximum voltage that can be applied by each magnetorquer
            coils_per_layer : [32.0,32.0,32.0,32.0,32.0,32.0]  # number of coils per layer
            layers : [2.0,2.0,2.0,2.0,2.0,2.0]                 # number of layers
            trace_width : [0.0007317, 0.0007317, 0.0007317, 0.0007317, 0.0007317, 0.0007317]  # m
            gap_width : [0.00008999, 0.00008999, 0.00008999, 0.00008999, 0.00008999, 0.00008999]  # m
            trace_thickness : [0.00003556, 0.00003556, 0.00003556, 0.00003556, 0.00003556, 0.00003556]  # 1oz copper - 35um = 1.4 mils
            max_current_rating : [1,1,1,1,1,1]  # A
            max_power : [5,5,5,5,5,5]  # W
       
solver:
      world_update_rate : 10 #Hz
      controller_update_rate : 10 #Hz
      payload_update_rate : 0.001 #Hz

mission:
      start_date : 60431.0 # MJD corresponding to midnight May 01 2024
      duration : 18000 # s
      
      # initial state properties
      initial_orbital_elements : [1.0E+7, 0.005, 96, 192, 21, 135] # [a, e, i, RAAN, AOP, M] NOTE: brahe takes Mean Anomaly and not true anomaly. Need to change code if we absolutely require true anomaly
      initial_attitude : [1.0, 0.0, 0.0, 0.0] # these quaternions represent a transformation from body-frame to ECI
      initial_angular_rate : [0.0, 2.0, 0.0] # [deg/s]
      initial_rw_speed : [0.0]
      # Mode management
      pointing_mode: "spin-stabilized" # "detumble" or "spin-stabilized" or "3D-stabilized"
      pointing_target: "Sun" # "Nadir" or "Sun"
      tgt_ang_vel: [0.0, 0.0, 10.0] # [deg/s]

complexity:
      use_drag : True
      use_srp : True


controller:
      # assuming controller states are angular velocity and quaternion imaginary components
      algorithm: "Lyapunov" # "BaseSP" # "Bcross" # # "BCROSS" or "PID" or "BaseSP"
      bcrossgain: [[0.0028, 0.0, 0.0],
                  [0.0, 0.0028, 0.0],
                  [0.0, 0.0, 0.0028]]

      state_feedback_gains: [[0.7071, 0.0, 0.0, 0.0028, 0.0, 0.0],
                              [0.0, 0.7071, 0.0, 0.0, 0.0028, 0.0],
                              [0.0, 0.0, 0.7071, 0.0, 0.0, 0.0028]]
      # state_int_feedback_gains: [[1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
      #                             [0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
      #                             [0.0, 0.0, 1.0, 0.0, 0.0, 0.0]]